---
name: CI
"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: arduino/setup-protoc@v1.1.2
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Test race
        run: make test-race
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/setup-protoc@v1.1.2
      - run: make proto
      - name: Lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: v1.36
